Add Ubix NS contract (Latest version)
SilentNotaryEcosystem/Cil-core pull request #90
Opened 2023-06-15 08:59 UTC by msklyarov

2023-06-23 11:44 UTC, trueshura requested changes

2023-06-23 11:44 UTC, trueshura commented on tests/ubix-ns/ns.js
> +        return JSON.stringify(ec.sign(hash, this._privateKey, 'hex'));
Вот в этом месте стало все плохо. 
1. Оно нигде не инициализируется.
2. Приватник в контракте - easy readable. Т.е. он становится скомпрометированным. Я ж уже объяснял.

2023-06-23 11:44 UTC, trueshura commented on tests/ubix-ns/ns.js
> +            !ec.verify(
1. Я не уверен, но мне кажется 1й аргумент `ec.verify` - Buffer
2. Я абсолютно уверен, что второй аргумент `ec.verify` - это структура `{r, s, recoveryParam}` а не то, что ты пытаешься ей скормить.

2023-06-23 11:44 UTC, trueshura commented on tests/ubix-ns/ns.js
> +        this._ns[hash] = [strAddressLower, callerAddress];
Мне все-таки кажется, что нельзя разрешать задавать произвольный адрес в `strAddressLower`.
Т.е. нужно использовать только `callerAddress`. Т.е. если у тебя есть какой-то адрес (который ты контролируешь) - тем приватником и подписывай транзакцию (но это нужно обсудить с руководством).

2023-06-23 11:46 UTC, trueshura commented on tests/ubix-ns/ns.js
> +        if (this._proxyAddress) {
Мы только 3 функции проксируем? Наверное есть в этом смысл.

2023-06-23 12:17 UTC, msklyarov commented on tests/ubix-ns/ns.js
> +        return JSON.stringify(ec.sign(hash, this._privateKey, 'hex'));
Убрал этот код вообще, он не нужен

2023-06-23 12:29 UTC, msklyarov commented on tests/ubix-ns/ns.js
> +        if (this._proxyAddress) {
Добавил ещё проксирование addProvider
В остальных там ошибаться негде - там 2 сеттера и 1 геттер, нужны ли там прокси-функции?

2023-06-23 12:43 UTC, msklyarov commented on tests/ubix-ns/ns.js
> +            !ec.verify(
я эту структуру и отдаю, просто она обёрнута сначала в JSON а потом в base64, чтобы строка была простая без объектов внутри
Вот как оно упаковывается в тесте:
```return Buffer.from(JSON.stringify(ec.sign(strToSign, strPrivateKey, 'hex')), 'binary').toString('base64');```

Вот обратная распаковка в verify
```JSON.parse(Buffer.from(strVerificationCode, 'base64').toString('binary')),```

Получится та самая структура

2023-07-12 06:49 UTC, trueshura commented on tests/ubix-ns/ns.js
> +                result[strProvider] = `Ux${arrResult[0]}`;
Мне не нравится идея выдавать с префиксом. Ядро ничего не знает о префиксах (и не должно). Поэтому мы когда-то легко добавили такой префикс. Ну и поскольку это все для транзакции, то на фронте придется избавляться от префикса, а это плохо, поскольку изменяются данные, а не представление.

2023-07-12 06:51 UTC, trueshura commented on tests/ubix-ns/ns.js
> +        if (Object.keys(result).length === 0) throw new Error('Account is not found');
Нужно какое-то единообразие: или везде `throw new Error (err_msg)`, или `throw err_msg`

2023-07-12 06:58 UTC, trueshura commented on tests/ubix-ns/ns.js
> +        const hash = this._sha256(`${strProviderLower}:${strNameLower}`);
Эти 3 строки я видел в `create`, `confirm` и почти в том же виде в `resolve`.
Не то, чтобы я прям за DRY.
Но мне кажется, что ошибок будет меньше, если из таки вынести в функцию.

2023-07-12 09:23 UTC, trueshura requested changes

2023-07-12 09:23 UTC, trueshura commented on tests/ubix-ns/ns.js
> +    }
Это в первую очередь sha3, и только потом 256. Или назови ее нейтрально, типа `calcHash`

2023-07-12 09:23 UTC, trueshura commented on tests/ubix-ns/ns.js
> +        return sha3.sha3_256(strInput);
правь на `sha3` и будем пробовать деплоить в тестнет.

2024-01-09 07:36 UTC, closed without merging